#!/usr/bin/env bash
# uploads a file to a server

usage(){
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
}

if [ "$#" -lt 4 ]; then
	usage
fi

path_to_file=$1
ip=$2
username=$3
ssh_path=$4

scp -o "StrictHostKeyChecking=no" -i "$ssh_path" "$path_to_file" "$username@$ip:~/"
