#!/usr/bin/env bash
# FizzBuzz

COUNT=1
while [ $COUNT -lt 101 ]
do
    if [ $((COUNT%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((COUNT%5)) = 0 ]
    then
        echo "Buzz"
    elif [ $((COUNT%3)) = 0 ] && [ $((COUNT%5)) = 0 ]
    then
        echo "FizzBuzz" 
    else
        echo "$COUNT"
    fi
    ((COUNT++))
done