#!/usr/bin/env bash

COUNT=1
while [ $COUNT -lt 21 ]
do
    case $COUNT in

        4)
            echo $COUNT
            echo "bad luck from China"
            ;;

        9)
            echo $COUNT
            echo "bad luck from Japan"
            ;;

        17)
            echo $COUNT
            echo "bad luck from Italy"
            ;;

        *)
            echo $COUNT
            ;;
    esac

    ((COUNT++))
done