#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes.

hours=0
echo "Hour: $hours"
((hours++))

while [ $hours -lt 13 ]
do
    minutes=0
    while [ $minutes -lt 61 ]
    do
        if [ $minutes -eq 60 ]
        then
            echo "Hour: $hours"
        else
            echo $minutes
        fi
        ((minutes++))
    done
    ((hours++))
done