#!/usr/bin/env bash
#Diplay hours

hours=0

echo "Hour: $hours"
((hours++))
while [ $hours -le 12 ]
do
    minutes=0
    while [ $minutes -le 60 ]
    do
        if [ $minutes -eq 60 ]
        then
            echo "Hour: $hours"
        else
            echo $minutes
        fi
        ((minutes++))
    done
    ((hours++))
done