#!/usr/bin/env bash
# display files name without i-

for file in *
do
    if [ -f "$file" ] && [[ "$file" != .* ]]
    then
        new_name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$new_name"
    fi
done
