#!/usr/bin/env bash
# display files name without i-

#Write a Bash script that displays:

#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)
#Requirements:

#You must use the for loop (while and until are forbidden)
#Do not display hidden files (file != .)


for file in *
do
    if [ -f "$file" ] && [[ "$file" != .* ]]
    then
        new_name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$new_name"
    fi
done
