#!/usr/bin/env bash
#Write a Bash script that gives you information about the school file.

file="school"

if [ -e "$file" ]; then
    if [ -f "$file" ]; then
        echo "$file file exists"
        content=$(cat "$file")

        if [ ! -z "$content" ]; then
            echo "$file file is not empty"
        else
            echo "$file file is empty"
        fi
    fi
else
    echo "$file file does not exist"
fi
